"""
 * This file is part of a CODESKIN library that is being made available
 * as open source under the GNU Lesser General Public License.
 *
 * Copyright 2017 by CodeSkin LLC, www.codeskin.com.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * ERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import os
import sys
import platform

Import('env')

module_env = env.Clone();
 			
if ((os.name == 'posix') and (platform.system() == 'Linux' )):  
	module_env.Append(LINKFLAGS = ' -Wl,-rpath -Wl,\$${ORIGIN} ')
		
elif((os.name == 'posix') and (platform.system() == 'Darwin' )):
	module_env.Append(LINKFLAGS = ' -install_name @rpath/'+module_env.SharedLibNameExt('CanLua')+' ') 
	module_env.Append(LINKFLAGS = ' -Wl,-rpath -Wl,@loader_path')

elif ((os.name == 'nt') and (platform.system() == 'Windows' )):
	module_env.Append(LINKFLAGS="")

module_env.Append(LIBPATH = ['lib']);	 						
module_env.Append(LIBS = [module_env.SharedLibName('Lua')]);		
module_env.Append(CPPPATH = ['include','../can']);

module_dll = module_env.SharedLibrary(module_env.SharedLibName('CanLua'),
						['can_lua.cpp',
						 ]);

test = SConscript(['test/SConscript']);
  						 
objs = []
Return('objs')	

