"""
 * This file is part of a CODESKIN library that is being made available
 * as open source under the GNU Lesser General Public License.
 *
 * Copyright 2005-2017 by CodeSkin LLC, www.codeskin.com.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.

 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * ERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.

 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
"""

import os
import sys
import platform

Import('env')

os_env = env.Clone();

if ((os.name == 'posix') and (platform.system() == 'Linux' )): 
	os_env.Append(LINKFLAGS= " -Wl,-rpath=\\$$ORIGIN") 
	os_env.Append(LIBS=['dl'])
	
elif((os.name == 'posix') and (platform.system() == 'Darwin' )):
	os_env.Append(LINKFLAGS="-Wl,-rpath -Wl,@executable_path") 
		
elif((os.name == 'nt') and (platform.system() == 'Windows' )):
	os_env['PDB'] = 'test.pdb'	
		
test = os_env.Program('TestCanDll', [
	'main.cpp',
	]);	
	
can_dll = os_env.Command(os_env.SharedLibNameExt('Can'), "../"+os_env.SharedLibNameExt('Can'), Copy("$TARGET", "$SOURCE"))
slcan_dll = os_env.Command(os_env.SharedLibNameExt('SLCan'), "../../slcan_can/"+os_env.SharedLibNameExt('SLCan'), Copy("$TARGET", "$SOURCE"))

if((os.name == 'nt') and (platform.system() == 'Windows' )):
	if int(os_env['ARCH']) == 32:	
		os_env.Requires(test, [
			can_dll, 
			slcan_dll
			])	
	else:
		os_env.Requires(test, [
			can_dll, 
			slcan_dll
			])
			
elif((os.name == 'posix') and (platform.system() == 'Darwin' )):
	os_env.Requires(test, [
		can_dll, 
		slcan_dll
		])			
										
objs = []

objs.append(test)
					
Return('objs');									